# Generated by Django 4.2.5 on 2023-09-30 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos_app', '0002_alter_gasto_monto_alter_ingreso_monto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='descripcion',
        ),
    ]
